version: "3.8"
services:
  library:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
